### ISSUE TITLE
Error when log in

### ISSUE THREAD

**Issue by ylin** [akdelarosa01/pms-inventory#4]
When I try to log in I get this error message

![CleanShot 2023-01-30 at 13 21 58@2x](https://user-images.githubusercontent.com/312667/215598120-3cf4a735-3f1b-44d1-b44b-b3ff8f61d662.png)

**Comment by akdelarosa01** [comment]
Hi sir, Please try to command

php artisan key:generate

in pms-inventory folder

**Comment by ylin** [comment]
I click login and I get the CSRF mismatch error

Do you know why?

**Comment by akdelarosa01** [comment]
Sir I updated the .env.example file.
Please add this to your .env file

SESSION_DOMAIN=localhost
SANCTUM_STATEFUL_DOMAINS=localhost

**Comment by ylin** [comment]
Thank you, that worked
