### ISSUE TITLE
Change overall layout

### ISSUE THREAD

**Issue by ylin** [akdelarosa01/pms-inventory#9]
<img width="821" alt="CleanShot 2023-02-08 at 07 42 12@2x" src="https://user-images.githubusercontent.com/312667/217578146-b47c0554-3334-446d-8eca-edb5131eb09a.png">

I think we should change overall layout of all views so it's a simple table that spans the entire width of the window, like above.

Then, if user clicks a row, a modal opens up with fields to edit. 

Similarly if user clicks add button, modal opens up with fields to edit.

We can put filters like Category chooser on top of the table.

This is consistent with most ERP UI design, where majority of views are simple tables that takes up the whole view, like Odoo: 

<img width="1052" alt="CleanShot 2023-02-08 at 07 43 41@2x" src="https://user-images.githubusercontent.com/312667/217578639-10df4f38-6d61-43bb-8391-2845c6f3b9e8.png">

This will replace the left & right pane design that we had in PMS

**Comment by ylin** [comment]
This also means the Add Items menu item is redundant

![CleanShot 2023-02-08 at 07 45 04@2x](https://user-images.githubusercontent.com/312667/217578994-71343387-1785-48db-b809-4062734bcefd.png)

As for Delete, odoo does it this way:

![CleanShot 2023-02-08 at 07 47 04@2x](https://user-images.githubusercontent.com/312667/217579467-41284696-c676-4982-be39-4830b930c7ae.png)

Or, we can put the delete button in the Edit modal? But that means we can delete only one at a time. This is simpler though. Maybe we can do whatever is simple first.

You can create a free account on Odoo to see its interface.

**Comment by akdelarosa01** [comment]
Good morning sir,
I change the layout and use ChakraUI
